### ISSUE TITLE
用不了

### ISSUE THREAD

**Issue by wuwude** [JasonYANG170/GaoGaoNetAUTO#1]
提示电脑未连接到校园网，请刷新二维码页面重试

**Comment by JasonYANG170** [comment]
> 提示电脑未连接到校园网，请刷新二维码页面重试

稍等，今天会发第二版，支持手机和电脑端自定义设备登录

**Comment by wuwude** [comment]
哈哈，好的，我删掉这个贴

**Comment by JasonYANG170** [comment]
> 哈哈，好的，我删掉这个贴

还在上课，晚上发😭

**Comment by JasonYANG170** [comment]
发布了2.0版本，现在你可以自定义需要连接的设备IP。使用本程序前提是你必须能正确提取出你的tonken

**Comment by JasonYANG170** [comment]
tonken应当为ey开头的一长串字符串

**Comment by wuwude** [comment]
tonken我知道，我大一的，加个v？大佬~

**Comment by wuwude** [comment]
> tonken应当为ey开头的一长串字符串
依旧显示为：
响应数据: {"code":400,"msg":"电脑未连接到校园网，请刷新二维码页面重试"}

**Comment by wuwude** [comment]
> tonken应当为ey开头的一长串字符串

明天联系上你，可以给你发图看，是在请求头里，Authorization: Bearer的后面，Content-Type: application/json的前面的一段文字就是tonken，对吧

**Comment by JasonYANG170** [comment]
我认为这是你ip电脑错误引起的，糕糕ipv4地址应当是10开头。（电脑设备确实较为麻烦，但是我在同学电脑上是可以成功的），由于这不是一个合规的程序，如果你有Telegram可以用https://t.me/JasonYANG17联系我😧🤔

**Comment by wuwude** [comment]
> 我认为这是你ip电脑错误引起的，糕糕ipv4地址应当是10开头。（电脑设备确实较为麻烦，但是我在同学电脑上是可以成功的），由于这不是一个合规的程序，如果你有Telegram可以用[https://t.me/JasonYANG17联系我😧🤔](https://t.me/JasonYANG17%E8%81%94%E7%B3%BB%E6%88%91%F0%9F%98%A7%F0%9F%A4%94)

嗯，没怎么用过，我试试

**Comment by wuwude** [comment]
> 我认为这是你ip电脑错误引起的，糕糕ipv4地址应当是10开头。（电脑设备确实较为麻烦，但是我在同学电脑上是可以成功的），由于这不是一个合规的程序，如果你有Telegram可以用[https://t.me/JasonYANG17联系我😧🤔](https://t.me/JasonYANG17%E8%81%94%E7%B3%BB%E6%88%91%F0%9F%98%A7%F0%9F%A4%94)

额，人呢？

**Comment by JasonYANG170** [comment]
已回复，Nekogram网络不好，很少上tg了😂

**Comment by wuwude** [comment]
> 已回复，Nekogram网络不好，很少上tg了😂

大佬，我只有无线套餐，可以弄在路由器上中继吗，我有一个小米的路由器~

**Comment by JasonYANG170** [comment]
可以使用，我试过用小米4c路由，使用的openwrt系统是可以连接到网络的，**连接有一个前提，你需要知道路由器的ip地址**

**Comment by wuwude** [comment]
> 可以使用，我试过用小米4c路由，使用的openwrt系统是可以连接到网络的，**连接有一个前提，你需要知道路由器的ip地址**

openwrt系统 是要给路由器刷机之后吗，我没有经验，不敢乱来，IP地址不知道，不是mac地址呀。。。我没经验，害。

**Comment by JasonYANG170** [comment]
> > 可以使用，我试过用小米4c路由，使用的openwrt系统是可以连接到网络的，**连接有一个前提，你需要知道路由器的ip地址**
> 
> openwrt系统 是要给路由器刷机之后吗，我没有经验，不敢乱来，IP地址不知道，不是mac地址呀。。。我没经验，害。

你如果用官方的系统可以尝试下wifi中继后**进控制台**看能不能看到ip地址，如果可以看到ip地址就可以直接把这个ip填入软件中设备二里认证就行了

**Comment by wuwude** [comment]
> > > 可以使用，我试过用小米4c路由，使用的openwrt系统是可以连接到网络的，**连接有一个前提，你需要知道路由器的ip地址**
> > 
> > 
> > openwrt系统 是要给路由器刷机之后吗，我没有经验，不敢乱来，IP地址不知道，不是mac地址呀。。。我没经验，害。
> 
> 你如果用官方的系统可以尝试下wifi中继后**进控制台**看能不能看到ip地址，如果可以看到ip地址就可以直接把这个ip填入软件中设备二里认证就行了

这个方法的确可以试试，可是我上次说你这个软件在我这边用不了啊（笑哭）
我无论是认证成功，还是退出成功，都对我的gaogao认证没有任何作用，还是原样呀

**Comment by JasonYANG170** [comment]
通过设备二的手机认证输入ip就行，设备一是电脑认证，由于糕糕才用的QR码无法修改，所以设备一只能认证电脑设备，修改ip不起作用

**Comment by wuwude** [comment]
> 通过设备二的手机认证输入ip就行，设备一是电脑认证，由于糕糕才用的QR码无法修改，所以设备一只能认证电脑设备，修改ip不起作用

好，我回去试试，再给你答复

**Comment by wuwude** [comment]
> 通过设备二的手机认证输入ip就行，设备一是电脑认证，由于糕糕才用的QR码无法修改，所以设备一只能认证电脑设备，修改ip不起作用

响应数据: {"code":400,"msg":"当前认证上网人数比较多，请稍后在试。"}{"code":400,"msg":"退出失败，登录状态获取失败。"}
这是怎么回事呀

**Comment by wuwude** [comment]
我发现你软件里面的那个糕糕二维码我软件扫了就只会显示过期，有没有可能我这的糕糕和你那边的糕糕的二维码是不一样的？

**Comment by wuwude** [comment]
> > 通过设备二的手机认证输入ip就行，设备一是电脑认证，由于糕糕才用的QR码无法修改，所以设备一只能认证电脑设备，修改ip不起作用
> 
> 好，我回去试试，再给你答复

我们这边的糕糕是这样的，手机连着糕糕wifi，然后开热点给其他设备用，就会收到糕糕的违规通知短信，然后就自动断开认证了。
你那边是这样的不？

**Comment by JasonYANG170** [comment]
1.**提示400**大概率是你的**token变动了**，抓取token后**不要退出账户，不要在其他设备登录糕糕软件**，token会在登录时变动。
2.短信警告这个我在大一时有遇到，但是现在大二就没遇到过了，至少我现在一直在用热点，没有任何影响。

**Comment by wuwude** [comment]
上次的确是token变动了，但是问题还是你的软件对我这里的糕糕不生效
现在显示
响应数据: {"code":200,"msg":"认证成功。"}
响应数据: {"code":200,"msg":"认证已退出。"}
响应数据: {"code":200,"msg":"认证已退出。"}
但是还是没有用，软件即使显示认证退出，我的手机电脑依旧可以上网，认证成功也是没有作用。
只有糕糕app有用

**Comment by JasonYANG170** [comment]
确认输入的是IPV4地址？我在我学校的多台电脑测试没有相关问题出现，也有可能是糕糕校园网在不同学校可能存在差异。🧐

**Comment by wuwude** [comment]
> 确认输入的是IPV4地址？我在我学校的多台电脑测试没有相关问题出现，也有可能是糕糕校园网在不同学校可能存在差异。🧐

那肯定是后者，手机的IPv4地址是打开WiFi设置就可以看到，应该不会搞错，而且看到的IP地址也和你说的一样，是糕糕的那种10开头的。再加上你电脑端那里不是有个自动获取的吗，获取出来的IP地址都是一样的。
